# 14. Lambda function in Python

 * __A Lambda function is small anonymous functions.__
 * __A Lambda function can take any number of arguments, but only have one expression.__
 * __The expression is evaluated and returns.__
 * __Lambda expression(Or lambda function) essentially blocks of code that can be assigned to variable, passed as an arguments, or returned from a function call, In Languages that supports high-order functions.__
 * __The main role of lambda function is better described in the scenerios when we employ them anonymously inside another functions.__
 
 * __Lambda function in Python:__
   * __Syntax:__
   * `Normal Function`
   * `Anonymous Function`
     * Usages:
       * __Lambda with filter()__
       * __Lambda with map()__
       * __Lambda with reduce()__
       * __Lambda with apply()__
   * __CommonErrors__
     * __SyntaxError__
     * __TypeError__

In [1]:
# defined user defined function 

def addTwo(x,y):  # x,y is parameter
    return x+y
addTwo(10,12)

22

In [3]:
addTwo(78,89)

167

In [5]:
# using lambda function above same code 

(lambda a,b:a+b)(10,12)

22

In [7]:
# how to write this program using user input 

def SumTwo(x,y):
    sum1 = x+y
    return f"Sum of The Two numbers {x} and {y} is {sum1}"

a = int(input("Enter first number: "))
b = int(input("Enter second number:"))
SumTwo(a,b)

Enter first number:  78
Enter second number: -96

'Sum of The Two numbers 78 and -96 is -18'

In [9]:
a = int(input("Enter first number: "))
b = int(input("Enter second number:"))


x5 = (lambda x1,y1:x1+y1)(a,b)
print(f"Sum of The Two numbers {a} and {b} is {x5}")

Enter first number:  78
Enter second number: 96

Sum of The Two numbers 78 and 96 is 174

In [10]:
def func1(x):
    return x+20

a = int(input("Enter any value: "))
func1(a)

Enter any value:  78

98

In [12]:
a = int(input("Enter any value: "))

# Normal function 

# (lambda Expression)(arguments)
(lambda a1 : a1+20)(a)

Enter any value:  78

98

In [13]:
# arrayList = [1,2,3,4,5,6,7,8,9,10]
# even or odd number pick out 



# even and or number pick out

arraylist = [1,2,3,4,5,6,7,8,9,10]
even = []
odd = []

for i in arraylist:
    #print(i)
    if i % 2 == 0:
        even.append(i)
    else:
        odd.append(i)
print(f'all numbers is {arraylist}')
print(f'even numbers is {even}')
print(f'odd numbers is {odd}')

all numbers is [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even numbers is [2, 4, 6, 8, 10]
odd numbers is [1, 3, 5, 7, 9]

In [14]:
List = [1,2,3,4,5,6,7,8,9,10]

for num in List:
    if num % 2 == 0:
        print("Even number:", num)
    else:
        print("Odd number:", num)

Odd number: 1
Even number: 2
Odd number: 3
Even number: 4
Odd number: 5
Even number: 6
Odd number: 7
Even number: 8
Odd number: 9
Even number: 10

In [16]:
arraylist = [1,2,3,4,5,6,7,8,9,10]
even = []
odd = []

for i in arraylist:
    #print(i)
    if i % 2 == 0:
        even.append(i)
    else:
        odd.append(i)
print(f'all numbers is {arraylist}')
print(f'even numbers is {even}')
print(f'odd numbers is {odd}')

all numbers is [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even numbers is [2, 4, 6, 8, 10]
odd numbers is [1, 3, 5, 7, 9]

In [17]:
arrayList = [1,2,3,4,5,6,7,8,9,10]

def find(numbers):
    even = []
    odd = []
    
    for i in numbers:
        if i % 2 == 0:
            even.append(i)
        else:
            odd.append(i)
    
    return even, odd

even, odd= find(arrayList)

print("Even numbers:", even)
print("Odd numbers:", odd)

Even numbers: [2, 4, 6, 8, 10]
Odd numbers: [1, 3, 5, 7, 9]

In [27]:
arrayList = [1,2,3,4,5,6,7,8,9,10]
# Lambda with filter()
# filter()

def evenNum(x):
    if x%2 ==0:
        return x

def oddNum(y):
    if y%2!=0:
        return y
   

oddNum(11)

11

In [28]:
evenNum(10)

10

syntax:

filter(function,sequence)

In [30]:
arrayList = [1,2,3,4,5,6,7,8,9,10]
list(filter(evenNum,arrayList))

[2, 4, 6, 8, 10]

In [31]:
list(filter(oddNum,arrayList))

[1, 3, 5, 7, 9]

In [35]:
list(filter(lambda a:a%2==0,arrayList))

[2, 4, 6, 8, 10]

In [36]:
list(filter(lambda x:x%2!=0,arrayList))

[1, 3, 5, 7, 9]

In [1]:
### Given a list of string, use filter() and lambda function to keep only the string that hagve a length greater than 5 charactars.

words = ['apple',"banana","cherry",'date','elderberry']


### The filter() function can take None as it's first argument to filter out items that are considered 'Falsy'.(eg.,0,None,"",False)
# use this with the following list

data_list = [0,1,"",None,"hello",[],[1,2]]

In [3]:
# given a list of string, use filter() and lambda function to keep only the string hat have length greater than 5 characters.

words = ['apple', 'banana', 'cherry', 'date', 'blackberry']

list(filter(lambda x: len(x) > 5, words))

['banana', 'cherry', 'blackberry']

In [5]:
### Given a list of string, use filter() and lambda function to keep only the string that hagve a length greater than 5 charactars.

words = ['apple',"banana","cherry",'date','elderberry']

list(filter(lambda a:len(a)>5, words))

['banana', 'cherry', 'elderberry']

In [13]:
### The filter() function can take None as it's first argument to filter 
# out items that are considered 'Falsy'.(eg.,0,None,"",False)
# use this with the following list

data_list = [0,1,"",None,"hello",[],[1,2]]

# list(filter(lambda a1:a1==False,data_list)

list(filter(lambda x: not x, data_list))

[0, '', None, []]

In [11]:
not(not(True))

True

In [14]:
### The filter() function can take None as it's first argument to filter 
# out items that are considered 'Falsy'.(eg.,0,None,"",False)
# use this with the following list

data_list = [0,1,"",None,"hello",[],[1,2]]

# list(filter(lambda a1:a1==False,data_list)

list(filter(lambda x: x, data_list))

[1, 'hello', [1, 2]]

In [16]:
# find the square of given list  data_list = [1,2,5,4,9,2,8,2,12,25,88,96]

# find the square of the given list data_list=[1,2,4,5,9,2,8,2,12,25,88,96]
data_list=[1,2,4,5,9,2,8,2,12,25,88,96]
list(map(lambda a : a**2 ,data_list))

[1, 4, 16, 25, 81, 4, 64, 4, 144, 625, 7744, 9216]

In [17]:
# find the squar of given list. data_list = [1,2,5,4,9,2,8,2,12,25,88,96]

data_list = [1,2,5,4,9,2,8,2,12,25,88,96]

def sqr():
    for i in data_list:
        print(f'squar of {i} = {i*i}')

sqr()

squar of 1 = 1
squar of 2 = 4
squar of 5 = 25
squar of 4 = 16
squar of 9 = 81
squar of 2 = 4
squar of 8 = 64
squar of 2 = 4
squar of 12 = 144
squar of 25 = 625
squar of 88 = 7744
squar of 96 = 9216

### Lambda with map?

 * `map()` applies a function to each item of an iterable(like list, tuple)
 * `map(function, iterable/sequence)`

 * Return a map object(iterator)
 * Usually converted to list/tuple

In [33]:
# find the squar of given list. data_list = [1,2,5,4,9,2,8,2,12,25,88,96]

def sqrNum(x):
    return x*x

In [35]:
data_list = [1,2,5,4,9,2,8,2,12,25,88,96]
list(map(sqrNum,data_list))

[1, 4, 25, 16, 81, 4, 64, 4, 144, 625, 7744, 9216]

In [36]:
def cubeNum(a):
    return a**3

In [37]:
list(map(cubeNum,data_list))

[1, 8, 125, 64, 729, 8, 512, 8, 1728, 15625, 681472, 884736]

In [38]:
data_list = [1,2,5,4,9,2,8,2,12,25,88,96]


list(map(lambda a:a**3,data_list))

[1, 8, 125, 64, 729, 8, 512, 8, 1728, 15625, 681472, 884736]

In [40]:
### Convert Celcius to Fahrenheit 

# 32°c - 


# celciouc to Fahrenheit 

a = int(input("Enter Celcius Value:"))
x = (lambda x: (x*9/5) + 32)(a)
print(f'Fahrenheit value of {a}: {x}°F' )

Enter Celcius Value: 37

Fahrenheit value of 37: 98.6°F

In [41]:
names = ['vishAL',"mohit","nil babre",'anil Prajapati']

# convert this value into lower(), uppercase(),title() using lambda function


names = ['vishal', 'mohit', 'nil babre', 'anil prajapati']

x =list(map(lambda a: a.upper(), names))
y = list(map(lambda a: a.lower(), names))
z = list(map(lambda a: a.title(), names))

print(f'names in upper: {x}')
print(f'names in lower: {y}')
print(f'names in title: {z}')

names in upper: ['VISHAL', 'MOHIT', 'NIL BABRE', 'ANIL PRAJAPATI']
names in lower: ['vishal', 'mohit', 'nil babre', 'anil prajapati']
names in title: ['Vishal', 'Mohit', 'Nil Babre', 'Anil Prajapati']

# Lambda with reduce()


`reduce()` is used to apply a function to items of an iterable and reduce it to a single value.

`from functools import reduce`


 __syntax:__

 * reduce(function, iterable/sequece)
 * ✔️Applies function step-by-step
 * ✔️Retunrs inside reduce

In [42]:
from functools import reduce

In [44]:
x = [10,11,12,13]  # [46]

def sumVal(x,y):
    return x+y

In [47]:
reduce(sumVal,x)

46

In [53]:
reduce(lambda a,b:a+b, x)

46

In [2]:
# Lambda with apply()

import pandas as pd

In [4]:
listData = [1,2,3,4,5,6,7,8,9,10]
print(listData)

df1 = pd.DataFrame(listData)
print(df1,type(df1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    0
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9  10 <class 'pandas.core.frame.DataFrame'>

In [7]:
dataList = [[1,2,3],[4,5,6],[7,8,9]]

df2 = pd.DataFrame(dataList)
df2

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [12]:
# df2[column][row]
df2[2][2]**2

np.int64(81)

In [14]:
df1 = df2.apply(lambda a:a**2)
df1

    0   1   2
0   1   4   9
1  16  25  36
2  49  64  81

In [15]:
df1=df2.apply(lambda a:a+10)
df1

    0   1   2
0  11  12  13
1  14  15  16
2  17  18  19

In [16]:
### Home work Time: 

# 1-5 sove and past in chatting box

# 5-10



# 1. Write a lambda function to calculate the square of a number.

square=[1,2,3,4,5,6,7,8,9,10]
list(map(lambda a:a*a , square))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [17]:
# 2. Use a lambda function with map() to add 5 to each number in the list: nums = [1, 2, 3, 4]

nums=[1,2,3,4,5,6,7,8,9,10]
list(map(lambda a:a+5 , nums))

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [18]:
# 3. Use filter() with a lambda to find even numbers from a list: 

nums = [5, 8, 11, 14, 17, 20]

list(filter(lambda a: a%2==0, nums))

[8, 14, 20]

In [19]:
# 4. Use reduce() with a lambda to compute the product of all elements in a list: nums = [2, 3, 4, 5] (Hint: from functools import reduce)
from functools import reduce
nums = [2, 3, 4, 5]
reduce(lambda a,b:a+b,nums)

14

In [25]:
# 5. Sort the following list of tuples by the second value using a lambda function: data = [(1, 3), (2, 1), (4, 2)]

data = [(1, 3), (2, 1), (4, 2),(1,1)]
sorted(data, key=lambda a:a[0])

[(1, 3), (1, 1), (2, 1), (4, 2)]

In [44]:
# 6. Write a lambda that checks if a string starts with 'A'.

string=["Grapes","Apple","Banana","Amit"]
list(filter(lambda a:a.startswith('A'),string))

['Apple', 'Amit']

In [52]:
string=["Grapes","Apple","Banana","Amit","ape","app"]
# string = "Grapes,Apple,Banana"
list(filter(lambda a:a[0].lower() == "a" ,string))

['Apple', 'Amit', 'ape', 'app']

In [53]:
x= "A"

ord(x)

65